language: csharp
mono: none
dotnet: 3.0
os:
- linux
install:
- dotnet restore TodoApi

env: 
 - CODECOV_TOKEN=e522be9b-7ce4-43f4-8488-8439ec237c5a

script:
 - dotnet build TodoApi
 - dotnet test Test

after_success
 - codecov
