language: csharp
mono: none
dotnet: 3.0
os:
- linux
install:
- dotnet restore TodoApi
before_build:
- dotnet tool install --global Codecov.Tool
script:
 - dotnet build TodoApi
 - dotnet test Test
after_script:
  - codecov
